language:       php
env:
  global:
  - GIT_NAME:   Travis CI
  - GIT_EMAIL:  funilrys@outlook.com
  - TRAVIS_REPO_SLUG: funilrys/dead-hosts
  - GIT_BRANCH: master
  - secure:     "J2hkwUEBsh3GUWug/l377rwqMgUEeThu7U38NfLVIaM4LMbCJOmppk31ojxYeAUo7wZQGspJ38MZ7frObzFimPVFvIzFb8HJWSrjLHd8SIwZEMzm/m7LH3XqnGiqBk2qwX/cSp3lgELS1nDY6sEyqCE9XS4ksf/tVBYjJVlbE+uunX01Kx7aoGvcfpqFA1GAXlEpEwVdOBPtVRHx5oLzB146ZcDMwpceZBl7FisNhiJENmZumF66eT+6lf+mZqeTuU+AvhYUDGWlLN0aQtdayh9WwxHcMgVznxNNR3TXxIt28FPVxGqo6oVUFTbyIVoFtdOLym8TGIocnTlHvJxb7Fp81m2MxSNCm0aS1pgbE4pwE8IkKSzGwlJeGeXnqYMFXPOpgvXAtHyzt2utCIRk2c/ETUKVvjMdS8ezeZ9LGh1P5pnOdwEFa7cx2ZNUNx2Yb+/NDbxAihu4lWl8bMTtwO2fFONWlJYweVlknCTvq4s3Mk2hP2z7ZSCUzf7qV6hc1grHIMXCfWQwmDCpzsPWOYy9BShpwP9NgiV/3IoOs0nK4QpPaHHOh3ARfsL6a3NGK4Pb00i8IzZYaYiqa38fnFx0ijj3S/YIV8WWw59PaBj01UI1rgzdOiUg1Tmh/V+VCm4VFoKSOIrsi/mEOIfv1eiF+nkZsvsDGu5LHRAcbFk="

dist:           trusty
sudo:           required
matrix:
  fast_finish:  true
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install expect
- sudo apt-get -y install whois
- sudo apt-get -y install dos2unix
cache:
- apt
script:
- bash .dev-tools/pre-deploy
before_deploy:
- bash .dev-tools/deploy-package
deploy:
  provider:     releases
  api_key:
    secure:     ${GH_TOKEN}
  skip_cleanup: true
  on:
    repo:       funilrys/dead-hosts
